name: axel_todo_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^9.2.0
  path_provider: ^2.1.5
  internet_connection_checker: ^3.0.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  google_fonts: ^7.1.0
  shimmer: ^3.0.0
  uuid: ^4.5.2
  path: ^1.9.1
  bloc: ^9.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
